### ISSUE TITLE
登录出现SSLError("bad handshake错误

### ISSUE THREAD

**Issue by longhaiqwe** [jachinlin/geektime_dl#17]
**环境描述**
- centos7
- python3.5
- login之前的操作均正常完成

**问题描述**
login的时候出现如下报错：
```
HTTPSConnectionPool(host='account.geekbang.org', port=443): Max retries exceeded with url: /account/ticket/login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```
geektime.log日志内容如下：
```
log_time=2019-01-22 10:35:47,859	levelname=ERROR	process=16677	exception=Traceback (most recent call last):
  File "/home/longhai/venv3/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 453, in wrap_socket
    cnx.do_handshake()
  File "/home/longhai/venv3/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/longhai/venv3/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/home/longhai/venv3/lib/python3.5/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/longhai/venv3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "/home/longhai/venv3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 805, in _prepare_proxy
    conn.connect()
  File "/home/longhai/venv3/lib/python3.5/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/home/longhai/venv3/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/longhai/venv3/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 459, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/longhai/venv3/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/longhai/venv3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/longhai/venv3/lib/python3.5/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='account.geekbang.org', port=443): Max retries exceeded with url: /account/ticket/login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/longhai/venv3/lib/python3.5/site-packages/geektime_dl/cli/command.py", line 63, in main
    o.work(args)
  File "/home/longhai/venv3/lib/python3.5/site-packages/geektime_dl/cli/command.py", line 26, in work
    return self.run(args)
  File "/home/longhai/venv3/lib/python3.5/site-packages/geektime_dl/cli/login.py", line 49, in run
    gk.login(account, password, area)
  File "/home/longhai/venv3/lib/python3.5/site-packages/geektime_dl/utils/__init__.py", line 22, in wrapper
    return func(self, *args, **kwargs)
  File "/home/longhai/venv3/lib/python3.5/site-packages/geektime_dl/data_client/gk_apis.py", line 54, in login
    resp = requests.post(url, headers=headers, json=data, timeout=10)
  File "/home/longhai/venv3/lib/python3.5/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/longhai/venv3/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/longhai/venv3/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/longhai/venv3/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/longhai/venv3/lib/python3.5/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='account.geekbang.org', port=443): Max retries exceeded with url: /account/ticket/login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
	location=/home/longhai/venv3/lib/python3.5/site-packages/geektime_dl/cli/command.py:74
```

**Comment by luoMonkeyKing** [comment]
请问怎么解决的？
