### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by jiangchuan2015** [jachinlin/geektime_dl#33]
下载 159
Expecting value: line 1 column 1 (char 0)

**Comment by jiangchuan2015** [comment]
cat geektime.log
log_time=2019-06-06 08:38:57,284        levelname=ERROR process=1       exception=Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/geektime_dl/cli/command.py", line 63, in main
    o.work(args)
  File "/usr/local/lib/python3.7/site-packages/geektime_dl/cli/command.py", line 26, in work
    return self.run(args)
  File "/usr/local/lib/python3.7/site-packages/geektime_dl/cli/ebook.py", line 109, in run
    data = dc.get_course_content(course_id, force=force)
  File "/usr/local/lib/python3.7/site-packages/geektime_dl/data_client/__init__.py", line 59, in get_course_content
    post_detail = self.get_post_content(post['id'], force=force)
  File "/usr/local/lib/python3.7/site-packages/geektime_dl/data_client/__init__.py", line 36, in get_post_content
    data = self._gk.get_post_content(post_id)
  File "/usr/local/lib/python3.7/site-packages/geektime_dl/utils/__init__.py", line 36, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/geektime_dl/data_client/gk_apis.py", line 126, in get_post_content
    raise Exception('course query fail:' + resp.json()['error']['msg'])
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
        location=/usr/local/lib/python3.7/site-packages/geektime_dl/cli/command.py:74

**Comment by yawiki** [comment]
same error

**Comment by L5411** [comment]
打开 log 打印看了一下 resp 为空了，我临时在 gk_api.py 的 get_post_content 方法中重新调用了 login 方法重置 cookie，可以使用了
```
        if not (resp.status_code == 200 and resp.json().get('code') == 0):
            logger.debug("get_post_content error: " + resp.text)
            self.login(username, password)
            return self.get_post_content(post_id)
```

**Comment by XiaYinchang** [comment]
> 打开 log 打印看了一下 resp 为空了，我临时在 gk_api.py 的 get_post_content 方法中重新调用了 login 方法重置 cookie，可以使用了
> 
> ```
>         if not (resp.status_code == 200 and resp.json().get('code') == 0):
>             logger.debug("get_post_content error: " + resp.text)
>             self.login(username, password)
>             return self.get_post_content(post_id)
> ```

it works for me! Thank you!

**Comment by vitalQ** [comment]
重新登录一遍就好了

**Comment by jachinlin** [comment]
fixed
