### ISSUE TITLE
the JSON object must be str, bytes or bytearray, not NoneType

### ISSUE THREAD

**Issue by tic8** [jachinlin/geektime_dl#37]
用Docker下载视频课程失败，日志如下：
log_time=2019-07-04 14:42:50,903    levelname=ERROR process=1   exception=Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/geektime_dl/cli/command.py", line 63, in main
    o.work(args)
  File "/usr/local/lib/python3.7/site-packages/geektime_dl/cli/command.py", line 26, in work
    return self.run(args)
  File "/usr/local/lib/python3.7/site-packages/geektime_dl/cli/mp4.py", line 85, in run
    url = json.loads(post['video_media']).get('sd', {}).get('url')
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
    location=/usr/local/lib/python3.7/site-packages/geektime_dl/cli/command.py:74

**Comment by xiubojin** [comment]
python3 +1

**Comment by mgcnrx11** [comment]
```
log_time=2019-07-08 14:54:20,013	levelname=ERROR	process=1	exception=Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/geektime_dl/cli/command.py", line 63, in main
    o.work(args)
  File "/usr/local/lib/python3.7/site-packages/geektime_dl/cli/command.py", line 26, in work
    return self.run(args)
  File "/usr/local/lib/python3.7/site-packages/geektime_dl/cli/mp4.py", line 85, in run
    url = json.loads(post['video_media']).get('sd', {}).get('url')
KeyError: 'video_media'
	location=/usr/local/lib/python3.7/site-packages/geektime_dl/cli/command.py:74
```

same here

**Comment by warrenzhu25** [comment]
Python3 +1

**Comment by mgcnrx11** [comment]
抓包发现，就算能下载视频，这些视频都被AES128加密了，感觉不用白费力气了

**Comment by jachinlin** [comment]
mp4 api 好像改了 这个暂时不搞了，欢迎pr

**Comment by jachinlin** [comment]
fixed
