### ISSUE TITLE
geektime login报错

### ISSUE THREAD

**Issue by Leemin0311** [jachinlin/geektime_dl#39]
报错信息如下：

Traceback (most recent call last):
  File "/usr/local/bin/geektime", line 11, in <module>
    sys.exit(geektime())
  File "/usr/local/lib/python2.7/site-packages/geektime_dl/__init__.py", line 5, in main
    from geektime_dl import cli
  File "/usr/local/lib/python2.7/site-packages/geektime_dl/cli/__init__.py", line 4, in <module>
    from . import login, query, mp4, mp3, ebook
  File "/usr/local/lib/python2.7/site-packages/geektime_dl/cli/login.py", line 3, in <module>
    from geektime_dl.data_client.gk_apis import *
  File "/usr/local/lib/python2.7/site-packages/geektime_dl/data_client/__init__.py", line 10
    class DataClient(metaclass=Singleton):

**Comment by jachinlin** [comment]
log截全点
