### ISSUE TITLE
下载课程156的视频报错：Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by symsimmy** [jachinlin/geektime_dl#41]
geektime.log的日志
```
log_time=2019-07-27 09:47:40,106	levelname=ERROR	process=54787	exception=Traceback (most recent call last):
  File "/Users/user/anaconda3/lib/python3.7/site-packages/geektime_dl/cli/command.py", line 63, in main
    o.work(args)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/geektime_dl/cli/command.py", line 26, in work
    return self.run(args)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/geektime_dl/cli/mp4.py", line 60, in run
    data = dc.get_course_content(course_id)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/geektime_dl/data_client/__init__.py", line 59, in get_course_content
    post_detail = self.get_post_content(post['id'], force=force)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/geektime_dl/data_client/__init__.py", line 36, in get_post_content
    data = self._gk.get_post_content(post_id)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/geektime_dl/utils/__init__.py", line 36, in wrapper
    result = func(*args, **kwargs)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/geektime_dl/data_client/gk_apis.py", line 126, in get_post_content
    raise Exception('course query fail:' + resp.json()['error']['msg'])
  File "/Users/user/anaconda3/lib/python3.7/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/user/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/user/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/user/anaconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
	location=/Users/user/anaconda3/lib/python3.7/site-packages/geektime_dl/cli/command.py:74
```

**Comment by jachinlin** [comment]
用最新的源码试下
