### ISSUE TITLE
geektime ebook 时报错

### ISSUE THREAD

**Issue by ahcometrue** [jachinlin/geektime_dl#57]
请问我在执行时出现了错误，以下内容来自 geektime.log

```shell
log_time=2019-12-12 11:01:19,980	levelname=ERROR	process=15623	ERROR: Traceback (most recent call last):
  File "/Users/hg/Sites/.geektime/lib/python3.7/site-packages/geektime_dl/cli/command.py", line 232, in main
    o.work(args)
  File "/Users/hg/Sites/.geektime/lib/python3.7/site-packages/geektime_dl/cli/command.py", line 212, in work
    return self.run(cfg)
  File "/Users/hg/Sites/.geektime/lib/python3.7/site-packages/geektime_dl/cli/command.py", line 54, in wrap
    return func(*a, **kw)
  File "/Users/hg/Sites/.geektime/lib/python3.7/site-packages/geektime_dl/cli/command.py", line 54, in wrap
    return func(*a, **kw)
  File "/Users/hg/Sites/.geektime/lib/python3.7/site-packages/geektime_dl/cli/command.py", line 54, in wrap
    return func(*a, **kw)
  [Previous line repeated 10 more times]
  File "/Users/hg/Sites/.geektime/lib/python3.7/site-packages/geektime_dl/cli/ebook.py", line 164, in run
    make_mobi(source_dir=src_dir, output_dir=output_folder)
  File "/Users/hg/Sites/.geektime/lib/python3.7/site-packages/kindle_maker/ebook_maker.py", line 165, in make_ebook
    subprocess.call([kindlegen, '-dont_append_source', opf_file])
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 86] Bad CPU type in executable: '/Users/hg/Sites/.geektime/lib/python3.7/site-packages/kindle_maker/bin/mac/kindlegen'
	location=/Users/hg/Sites/.geektime/lib/python3.7/site-packages/geektime_dl/cli/command.py:235

```

**Comment by jachinlin** [comment]
原因可以参考 #52 
kindle-maker 已经做了fix，还没发版，直接源码安装吧
```python
pip uninstall kindle-makder
pip install ssh+git@github.com:jachinlin/kindle_maker.git
```

**Comment by ahcometrue** [comment]
非常感谢！我已经解决了
