### ISSUE TITLE
三个问题

### ISSUE THREAD

**Issue by jostyee** [jachinlin/geektime_dl#6]
1. 课程进度检测错误， 比如 https://time.geekbang.org/column/49 已经完结，但是被判断成未完待续
```
Info(prcgen):I1047: Added metadata dc:Title        "朱赟的技术管理课[未完待续]"
```

2. 有编码转换错误，日志
```
Error(core):E1008: Failed conversion to unicode. The resulting string may contain wrong characters.
```

3. 生成的mobi目录在书尾

**Comment by jachinlin** [comment]
v1.0 的问题目前不想花时间修复

可以使用 `dev` 分支试试，暂时还没添加文档

**Comment by jostyee** [comment]
query命令执行出错：
```
尚未登录，是否现在登录(Y/N): /usr/local/lib/python3.6/site-packages/geektime_ebook_maker/utils/m3u8_downloader.py:5: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util.ssl_ (/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py)', 'urllib3.util (/usr/local/lib/python3.6/site-packages/urllib3/util/__init__.py)'].
  monkey.patch_all()
EOF when reading a line
```

**Comment by jachinlin** [comment]
python3.6还有点小问题。。

**Comment by jostyee** [comment]
不会Python，我是在Docker跑的 https://github.com/jostyee/docker_geektime_ebook_maker/blob/dev/Dockerfile

geektime.log
```
log_time=2018-11-22 03:30:42,879	levelname=ERROR	process=1	exception=Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/geektime_ebook_maker/cli/command.py", line 55, in main
    o.run(args)
  File "/usr/local/lib/python3.7/site-packages/geektime_ebook_maker/cli/query.py", line 14, in run
    login_now = input("尚未登录，是否现在登录(Y/N): ")
EOFError: EOF when reading a line
	location=/usr/local/lib/python3.7/site-packages/geektime_ebook_maker/cli/command.py:58
```

**Comment by jachinlin** [comment]
用最新的代码试下吧 master readme文档也更新了

**Comment by jostyee** [comment]
一样的问题，搞不清楚了

```
log_time=2018-11-22 05:56:25,679	levelname=ERROR	process=1	exception=Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/geektime_dl/cli/command.py", line 63, in main
    o.work(args)
  File "/usr/local/lib/python3.7/site-packages/geektime_dl/cli/command.py", line 26, in work
    return self.run(args)
  File "/usr/local/lib/python3.7/site-packages/geektime_dl/cli/query.py", line 18, in run
    login_now = input("尚未登录，是否现在登录(Y/N): ")
EOFError: EOF when reading a line
	location=/usr/local/lib/python3.7/site-packages/geektime_dl/cli/command.py:66
```

**Comment by jostyee** [comment]
@jachinlin https://github.com/gevent/gevent/issues/1016#issuecomment-328529454 是不是因为这个？

**Comment by jachinlin** [comment]
https://github.com/jachinlin/geektime_dl/blob/master/geektime_dl/cli/login.py#L27

login 和 query 里边都有手动输入账号密码的步骤，应该是这个问题

你 -it 交互试下？

我一会把手动输入账号密码也变成 --accout --password 的形式

**Comment by jostyee** [comment]
https://github.com/jachinlin/geektime_dl/blob/master/geektime_dl/cli/query.py#L12

所以现在不支持 `geektime query -u account -p password` 了？

**Comment by jostyee** [comment]
通了，🙏

```
$ docker run -it -v `pwd`:/output geektime_ebook_maker login
enter your registered account(phone): 
enter password: 
登录成功

$ docker run -it -v `pwd`:/output geektime_ebook_maker query
专栏
	课程ID        已订阅       课程标题		更新频率/课时·时长
	140            否         Linux性能优化实战	(每周一 / 三 / 五更新)
```

**Comment by jachinlin** [comment]
https://github.com/jachinlin/geektime_dl/commit/fc9858a6310b827f4e4fa58c0e1e8e186eb0af89

已修改，试一下。

对的，参数形式改了。

先 login

`geektime login --account=xx --password=xxx`

再后续操作

`geektime query` 不用参数

其他操作看readme 吧

**Comment by jachinlin** [comment]
> 通了，🙏
> 
> ```
> $ docker run -it -v `pwd`:/output geektime_ebook_maker login
> enter your registered account(phone): 
> enter password: 
> 登录成功
> 
> $ docker run -it -v `pwd`:/output geektime_ebook_maker query
> 专栏
> 	课程ID        已订阅       课程标题		更新频率/课时·时长
> 	140            否         Linux性能优化实战	(每周一 / 三 / 五更新)
> ```

可以把dockerfile提个pr，我也学习下

**Comment by jostyee** [comment]
还是有点问题，应该和Docker无关

1. mp3下载对文件名包括特殊字符处理不对，比如：
```
$ docker run -v `pwd`:/output geektime_ebook_maker mp3 49
download mp3 done: 开篇词 | 从工程师到管理者，我的思考与实践.mp3
download mp3 done: 01 | 职场分身术：从给答案到做引导.mp3
download mp3 done: 02 | Bug引发事故，该不该追究责任？.mp3
[Errno 2] No such file or directory: './朱赟的技术管理课/03 | 每个工程师都应该了解的：A/B测试.mp3'
```

2. 生成的mobi，toc还是在mobi的最后面

**Comment by jostyee** [comment]
Okay

Dockerfile放在了 https://github.com/jostyee/docker_geektime_ebook_maker/blob/master/Dockerfile ，没法提PR，因为是pip install了这个repo，而不是直接使用当前目录代码。
